version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    # GCP
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/gcp-sa.json
    GCP_PROJECT: ${GCP_PROJECT}

    # Ingest config
    BRONZE_DATASET: ${BRONZE_DATASET:-bronze}
    BRONZE_TABLE: ${BRONZE_TABLE:-raw_cgm_readings}
    META_DATASET: ${META_DATASET:-meta}
    META_TABLE: ${META_TABLE:-ingestion_state}
    PIPELINE_NAME: ${PIPELINE_NAME:-cgm_microbatch}
    PATIENT_COUNT: ${PATIENT_COUNT:-60}
    CADENCE_MINUTES: ${CADENCE_MINUTES:-5}
    OVERLAP_MINUTES: ${OVERLAP_MINUTES:-10}
    DEFAULT_START_TS: ${DEFAULT_START_TS:-2025-01-01T00:00:00Z}

    # dbt
    DBT_DIR: /opt/airflow/dbt/cgm_dbt
    DBT_PROFILES_DIR: /opt/airflow/dbt/cgm_dbt
    DBT_DATASET: ${DBT_DATASET:-analytics}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./pipelines:/opt/airflow/pipelines
    - ./dbt:/opt/airflow/dbt
    - ./keys:/opt/airflow/keys:ro
    - airflow_logs:/opt/airflow/logs
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  postgres_data:
  airflow_logs: